//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class abgeleitet
    {
        public int FK_Dienstleistung { get; set; }
        public int FK_Ticket { get; set; }
    
        public virtual dienstleistung dienstleistung { get; set; }
        public virtual dienstleistung dienstleistung1 { get; set; }
        public virtual ticket ticket { get; set; }
    }
}
