//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class arbeitet
    {
        public int FK_Mitarbeiter { get; set; }
        public int FK_Kunde { get; set; }
    
        public virtual mitarbeiter mitarbeiter { get; set; }
        public virtual kunde kunde { get; set; }
        public virtual mitarbeiter mitarbeiter1 { get; set; }
    }
}
