//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mitarbeiter()
        {
            this.arbeitet = new HashSet<arbeitet>();
            this.arbeitet1 = new HashSet<arbeitet>();
            this.ticket = new HashSet<ticket>();
            this.ticket1 = new HashSet<ticket>();
        }
    
        public int PK_Mitarbeiter { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Position { get; set; }
        public string Festnetznummer { get; set; }
        public string Mobilnummer { get; set; }
        public string Email { get; set; }
        public string Passwort { get; set; }
        public Nullable<int> FK_Ort { get; set; }
        public Nullable<int> FK_Rechtegruppe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arbeitet> arbeitet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arbeitet> arbeitet1 { get; set; }
        public virtual ort ort { get; set; }
        public virtual rechtegruppe rechtegruppe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> ticket1 { get; set; }
    }
}
