//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rechnung
    {
        public int Rechnungsnr { get; set; }
        public string Ticketbeschreibung { get; set; }
        public string Abrechnung { get; set; }
        public Nullable<bool> Ratenzahlung { get; set; }
        public Nullable<int> FK_Bezahlungsart { get; set; }
        public Nullable<int> FK_Kunde { get; set; }
        public Nullable<int> FK_Ticket { get; set; }
    
        public virtual bezahlungsart bezahlungsart { get; set; }
        public virtual kunde kunde { get; set; }
        public virtual ticket ticket { get; set; }
    }
}
